name: Build System
on:
  workflow_dispatch:

jobs:
  build:
    name: Build System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: |
          sudo /usr/bin/buildah bud -f Containerfile --cap-add sys_admin --cap-add mknod --security-opt label=disable --no-cache