name: Build System
on:
  workflow_dispatch:

jobs:
  build:
    name: Build System
    runs-on: ubuntu-latest
    container:
        image: archlinux:base
        options: --privileged
    steps:
      - run: |
          pacman-key --init
          pacman-key --populate
          echo 'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist
          
          # This allows us to use this image for committing as well.
          pacman --noconfirm -Syu arch-install-scripts grub ostree rsync
          
          # This allows using this container to make a deployment.
          ln -s sysroot/ostree /ostree
          
          # This allows using pacstrap -N in a rootless container.
          echo 'root:1000:5000' > /etc/subuid
          echo 'root:1000:5000' > /etc/subgid
          
          # We need the ostree hook.
          install -d /mnt/etc
          
          # Install packages.
          pacstrap -c -G -M /mnt \
            base \
            linux \
            intel-ucode \
            amd-ucode \
            efibootmgr \
            grub \
            ostree \
            which
      