name: Build System
on:
  workflow_dispatch:

jobs:
  build:
    name: Build System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --privileged -v $(pwd)/mnt:/mnt -v $(pwd):/workdir archlinux:latest /bin/bash /workdir/base.sh
      - uses: docker/build-push-action@v5
        with:
          file: Containerfile
          context: .
          no-cache: true
      