name: Patcher
on:
  workflow_dispatch:

jobs:
  patch:
    name: Patcher
    runs-on: ubuntu-latest
    container:
        image: archlinux:base-devel
        options: --privileged
    steps:
        - name: Install git
          run: |
            pacman -Sy --noconfirm git
        - uses: actions/checkout@v4
          with:
            submodules: recursive