name: Patcher
on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  patcher:
    name: Patcher
    runs-on: ubuntu-latest
    container:
        image: archlinux:base-devel
        options: --privileged
    steps:
        - name: Install git
          run: |
            pacman -Sy --noconfirm git pacman-contrib
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Initialize mandatory git config
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email noreply@github.com
        - name: run patcher
          shell: bash
          run: |
            for dir in patches/*/
            do
                dir=${dir%*/}
                package=${dir##*/}
                ./$dir/patcher.sh pkgs $package pkgs
            done
        - name: update checksums
          run: |
            useradd -m build
            for dir in pkgs*/*-chimeraos/
            do
                dir=${dir%*/}
                chmod 777 $dir
                pushd $dir
                chown build PKGBUILD
                su build bash -c "updpkgsums"
                popd
            done
        - name: commit changes
          run: |
            git config --global --add safe.directory $(pwd)
            git add .
            git commit -m "update -chimeraos packages"
            git push